package materialize

import (
	"bufio"
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/leoru/gitident-cli/internal/fsutil"
	"github.com/leoru/gitident-cli/internal/paths"
)

// registryHeader starts the registry file; uninstall recognises files it
// may delete by the "# generated by gitident " prefix.
const registryHeader = "# generated by " + paths.AppName + " — repository config files holding a materialized profile; do not edit\n"

// RegistryPath is the file listing every repository config file gitident has
// materialized a profile into, so sync can keep them current without a scan.
func RegistryPath() string {
	return filepath.Join(paths.FragmentDir(), "materialized.list")
}

// LoadRegistry returns the registered config file paths (absolute).
func LoadRegistry() ([]string, error) {
	data, err := os.ReadFile(RegistryPath())
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var out []string
	sc := bufio.NewScanner(bytes.NewReader(data))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out = append(out, paths.Expand(line))
	}
	return out, sc.Err()
}

// SaveRegistry replaces the registry with files; an empty list removes it.
func SaveRegistry(files []string) error {
	seen := map[string]bool{}
	var list []string
	for _, f := range files {
		c := paths.Contract(f)
		if !seen[c] {
			seen[c] = true
			list = append(list, c)
		}
	}
	if len(list) == 0 {
		err := os.Remove(RegistryPath())
		if errors.Is(err, os.ErrNotExist) {
			return nil
		}
		return err
	}
	sort.Strings(list)
	data := registryHeader + strings.Join(list, "\n") + "\n"
	old, _ := fsutil.ReadFileIfExists(RegistryPath())
	if string(old) == data {
		return nil
	}
	return fsutil.WriteFileAtomic(RegistryPath(), []byte(data), 0o644)
}
