package cli

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/leoru/gitident-cli/internal/config"
	"github.com/leoru/gitident-cli/internal/fsutil"
	"github.com/leoru/gitident-cli/internal/gitx"
	"github.com/leoru/gitident-cli/internal/paths"
	"github.com/leoru/gitident-cli/internal/render"
)

const syncUsage = `usage: gitident sync [--dry-run] [--no-prune]

Render profiles.yaml into gitconfig:
  1. one fragment per profile in ~/.gitconfig.d/gitident/<profile>.gitconfig
  2. a managed block of includeIf rules in your global gitconfig
     (everything outside the block is left untouched)
  3. copies of profiles in repositories' .git/config made by "gitident apply"
     or ` + "`materialize: true`" + ` are brought up to date (see "gitident help apply")

flags:
  --dry-run    show what would change, write nothing
  --no-prune   keep fragments of profiles that no longer exist
`

func (a *App) cmdSync(args []string) error {
	fs := a.newFlags("sync", syncUsage)
	dryRun := fs.Bool("dry-run", false, "")
	noPrune := fs.Bool("no-prune", false, "")
	pos, err := parseFlags(fs, args)
	if err != nil {
		return err
	}
	if len(pos) > 0 {
		return usageError("unexpected arguments: %s", strings.Join(pos, " "))
	}
	cfg, err := a.loadConfig()
	if err != nil {
		return err
	}
	return a.sync(cfg, syncOptions{dryRun: *dryRun, prune: !*noPrune})
}

type syncOptions struct {
	dryRun bool
	prune  bool
}

// fragmentHeader identifies files gitident generated (and may therefore prune).
var fragmentHeader = []byte("# generated by " + paths.AppName + " ")

// sync writes fragments and the managed block for a validated config.
func (a *App) sync(cfg *config.Config, opts syncOptions) error {
	verb := "wrote"
	if opts.dryRun {
		verb = "would write"
	}
	changed := 0

	// 0. Refuse to rewrite a block that holds settings gitident did not write.
	global := paths.GlobalGitConfig()
	old, err := fsutil.ReadFileIfExists(global)
	if err != nil {
		return err
	}
	foreign, err := render.ForeignLines(old)
	if err != nil {
		if errors.Is(err, render.ErrCorruptBlock) {
			fmt.Fprintln(a.Stderr, render.CorruptBlockHelp(paths.Contract(global)))
		}
		return err
	}
	if len(foreign) > 0 {
		fmt.Fprintf(a.Stderr, "%s has settings inside the gitident managed block that sync would delete:\n", paths.Contract(global))
		for _, l := range foreign {
			fmt.Fprintf(a.Stderr, "    %s\n", l)
		}
		fmt.Fprintf(a.Stderr, "Move them above the \"# >>> gitident\" line (or into a profile's `extra`), then run sync again.\n")
		return &exitError{code: 1, msg: "refusing to overwrite settings in the managed block"}
	}

	// 1. Fragments.
	for _, f := range wantedFragments(cfg) {
		path, data := f.path, f.data
		old, err := fsutil.ReadFileIfExists(path)
		if err != nil {
			return err
		}
		if bytes.Equal(old, data) {
			continue
		}
		changed++
		a.printf("%s %s\n", verb, paths.Contract(path))
		if opts.dryRun {
			a.printf("%s\n", indent(string(data)))
			continue
		}
		if err := fsutil.WriteFileAtomic(path, data, 0o644); err != nil {
			return err
		}
	}

	// 2. Prune fragments of removed profiles.
	if opts.prune {
		stale, err := staleFragments(cfg)
		if err != nil {
			return err
		}
		for _, path := range stale {
			changed++
			if opts.dryRun {
				a.printf("would remove %s\n", paths.Contract(path))
				continue
			}
			if err := os.Remove(path); err != nil {
				return err
			}
			a.printf("removed %s\n", paths.Contract(path))
		}
	}

	// 3. Managed block.
	block := render.Block(cfg)
	updated, err := render.Splice(old, block)
	if err != nil {
		if errors.Is(err, render.ErrCorruptBlock) {
			fmt.Fprintln(a.Stderr, render.CorruptBlockHelp(paths.Contract(global)))
		}
		return err
	}
	if !bytes.Equal(old, updated) {
		changed++
		a.printf("%s managed block in %s\n", verb, paths.Contract(global))
		if opts.dryRun {
			a.printf("%s\n", indent(string(block)))
		} else if err := fsutil.WriteFileAtomic(global, updated, 0o644); err != nil {
			return err
		}
	}

	// 4. Materialized copies in repositories.
	nCopies, held, err := a.syncMaterialized(cfg, opts.dryRun)
	if err != nil {
		return err
	}
	changed += nCopies

	a.syncWarnings(cfg, global)

	nRepos := 0
	for _, p := range cfg.Profiles {
		nRepos += len(p.Repos)
	}
	summary := fmt.Sprintf("%s, %s, %s", plural(len(cfg.Profiles), "profile"), plural(len(cfg.Rules), "rule"), plural(nRepos, "repo"))
	if held > 0 {
		summary += ", " + plural(held, "materialized copy")
	}
	switch {
	case changed == 0:
		a.printf("up to date (%s)\n", summary)
	case opts.dryRun:
		a.printf("dry run: %s; nothing written (%s)\n", plural(changed, "change"), summary)
	default:
		a.printf("synced %s → %s\n", summary, paths.Contract(global))
	}
	return nil
}

type fragmentFile struct {
	path string
	data []byte
}

// wantedFragments lists every fragment sync maintains for cfg.
func wantedFragments(cfg *config.Config) []fragmentFile {
	var out []fragmentFile
	if cfg.Strict() {
		out = append(out, fragmentFile{paths.FragmentPath(paths.StrictFragment), render.StrictFragmentContent()})
	}
	for _, name := range cfg.ProfileNames() {
		out = append(out, fragmentFile{paths.FragmentPath(name), render.Fragment(name, cfg.Profiles[name])})
	}
	return out
}

// staleFragments lists generated fragment files whose profile no longer exists.
func staleFragments(cfg *config.Config) ([]string, error) {
	entries, err := os.ReadDir(paths.FragmentDir())
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var stale []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, paths.FragmentExt) {
			continue
		}
		base := strings.TrimSuffix(name, paths.FragmentExt)
		if _, ok := cfg.Profiles[base]; ok || (base == paths.StrictFragment && cfg.Strict()) {
			continue
		}
		path := filepath.Join(paths.FragmentDir(), name)
		data, err := os.ReadFile(path)
		if err != nil || !bytes.HasPrefix(data, fragmentHeader) {
			continue // not ours
		}
		stale = append(stale, path)
	}
	sort.Strings(stale)
	return stale, nil
}

// syncWarnings reports configurations that defeat what sync just set up.
func (a *App) syncWarnings(cfg *config.Config, global string) {
	for _, w := range globalIdentityWarnings(cfg, global) {
		a.warn("%s", w)
	}
	if usesHasconfig(cfg) {
		if v, err := gitx.GitVersion(); err == nil && !v.AtLeast(gitx.HasConfigMinVersion.Major, gitx.HasConfigMinVersion.Minor) {
			a.warn("git %s does not support includeIf \"hasconfig:remote.*.url:\" (needs %d.%d+); `remotes` rules and URL repos will be ignored",
				v, gitx.HasConfigMinVersion.Major, gitx.HasConfigMinVersion.Minor)
		}
	}
}

// globalIdentityWarnings reports user.name / user.email set directly in the
// global config (outside the managed block), which defeats strict_identity.
func globalIdentityWarnings(cfg *config.Config, global string) []string {
	files := []string{global}
	xdg := paths.Expand("~/.config/git/config")
	if x := os.Getenv("XDG_CONFIG_HOME"); x != "" {
		xdg = filepath.Join(x, "git", "config")
	}
	if !paths.SamePath(xdg, global) && os.Getenv("GIT_CONFIG_GLOBAL") == "" {
		files = append(files, xdg)
	}
	var warns []string
	for _, f := range files {
		if _, err := os.Stat(f); err != nil {
			continue
		}
		for _, key := range []string{"user.name", "user.email"} {
			vals, err := gitx.FileGetAll(f, key)
			if err != nil || len(vals) == 0 {
				continue
			}
			msg := fmt.Sprintf("%s sets %s = %s outside the managed block", paths.Contract(f), key, vals[len(vals)-1])
			if cfg.Strict() {
				msg += "; repositories matching no profile will silently use it (defeats strict_identity) — remove it"
			}
			warns = append(warns, msg)
		}
	}
	return warns
}

func usesHasconfig(cfg *config.Config) bool {
	for _, r := range cfg.Rules {
		if len(r.Remotes) > 0 {
			return true
		}
	}
	for _, p := range cfg.Profiles {
		for _, repo := range p.Repos {
			if paths.IsURL(repo) {
				return true
			}
		}
	}
	return false
}

func indent(s string) string {
	lines := strings.Split(strings.TrimRight(s, "\n"), "\n")
	for i, l := range lines {
		lines[i] = "    " + l
	}
	return strings.Join(lines, "\n")
}
