package agent

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/leoru/gitident-cli/internal/fsutil"
	"github.com/leoru/gitident-cli/internal/paths"
)

// Scope is where the Claude Code integration is installed.
type Scope string

const (
	ScopeUser    Scope = "user"    // ~/.claude/settings.json, ~/.claude/skills
	ScopeProject Scope = "project" // .claude/settings.json (shared with the team)
	ScopeLocal   Scope = "local"   // .claude/settings.local.json (just you)
)

// ClaudeFiles are the files one scope uses.
type ClaudeFiles struct {
	Settings string
	Skill    string // SKILL.md
}

// ClaudePaths returns the files for scope; project and local scopes live
// under projectDir.
func ClaudePaths(scope Scope, projectDir string) (ClaudeFiles, error) {
	switch scope {
	case ScopeUser:
		dir := os.Getenv("CLAUDE_CONFIG_DIR")
		if dir == "" {
			dir = filepath.Join(paths.Home(), ".claude")
		}
		return ClaudeFiles{filepath.Join(dir, "settings.json"), filepath.Join(dir, "skills", paths.AppName, "SKILL.md")}, nil
	case ScopeProject, ScopeLocal:
		name := "settings.json"
		if scope == ScopeLocal {
			name = "settings.local.json"
		}
		dir := filepath.Join(projectDir, ".claude")
		return ClaudeFiles{filepath.Join(dir, name), filepath.Join(dir, "skills", paths.AppName, "SKILL.md")}, nil
	}
	return ClaudeFiles{}, fmt.Errorf("unknown scope %q (want user, project or local)", scope)
}

// HookArgs are appended to the gitident binary to form the hook command.
const HookArgs = "agent hook claude"

// isOurHook reports whether a hook command is gitident's.
func isOurHook(cmd string) bool {
	return strings.Contains(cmd, paths.AppName) && strings.HasSuffix(strings.TrimSpace(cmd), HookArgs)
}

type hookCmd struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout,omitempty"`
}

type matcherGroup struct {
	Matcher string            `json:"matcher,omitempty"`
	Hooks   []json.RawMessage `json:"hooks"`
}

// EditSettings adds (install) or removes gitident's PreToolUse hook in a
// Claude Code settings file's content and returns the new content and whether
// it changed. Everything else in the file is kept, in its order.
func EditSettings(data []byte, command string, install bool) ([]byte, bool, error) {
	root, err := parseObject(data)
	if err != nil {
		return nil, false, err
	}
	hooks, err := root.childObject("hooks")
	if err != nil {
		return nil, false, err
	}
	var groups []json.RawMessage
	if raw, ok := hooks.get("PreToolUse"); ok {
		if err := json.Unmarshal(raw, &groups); err != nil {
			return nil, false, fmt.Errorf("hooks.PreToolUse: %w", err)
		}
	}

	// Drop every gitident hook, remembering whether the wanted one exists.
	found := false
	var kept []json.RawMessage
	changed := false
	for _, g := range groups {
		var mg matcherGroup
		if json.Unmarshal(g, &mg) != nil {
			kept = append(kept, g)
			continue
		}
		var rest []json.RawMessage
		for _, h := range mg.Hooks {
			var hc hookCmd
			if json.Unmarshal(h, &hc) == nil && isOurHook(hc.Command) {
				if install && hc.Command == command && mg.Matcher == "Bash" && !found {
					found = true
					rest = append(rest, h)
					continue
				}
				changed = true
				continue
			}
			rest = append(rest, h)
		}
		if len(rest) == 0 {
			changed = true
			continue
		}
		if len(rest) != len(mg.Hooks) {
			obj, err := parseObject(g)
			if err != nil {
				return nil, false, err
			}
			hb, _ := json.Marshal(rest)
			obj.set("hooks", hb)
			g, _ = obj.MarshalJSON()
		}
		kept = append(kept, g)
	}
	if install && !found {
		hb, _ := json.Marshal([]hookCmd{{Type: "command", Command: command, Timeout: 30}})
		g, _ := json.Marshal(matcherGroup{Matcher: "Bash", Hooks: []json.RawMessage{hb[1 : len(hb)-1]}})
		kept = append(kept, g)
		changed = true
	}
	if !changed {
		return data, false, nil
	}
	if len(kept) == 0 {
		hooks.del("PreToolUse")
	} else {
		raw, _ := json.Marshal(kept)
		hooks.set("PreToolUse", raw)
	}
	if hooks.len() == 0 {
		root.del("hooks")
	} else {
		root.setChild("hooks", hooks)
	}
	out, err := root.indent()
	return out, true, err
}

// HasHook reports whether settings content contains gitident's hook.
func HasHook(data []byte) bool {
	out, changed, err := EditSettings(data, "", false)
	_ = out
	return err == nil && changed
}

// SkillHeader identifies SKILL.md files gitident wrote.
const skillMarker = "<!-- generated by " + paths.AppName + " -->"

// Skill returns the SKILL.md content.
func Skill() []byte {
	return []byte(`---
name: gitident
description: Check and fix the git identity (author name, email, signing key) before committing, tagging, merging, rebasing or pulling, and when git reports "Author identity unknown" or a signing failure. This machine manages git identities with gitident.
---
` + skillMarker + `

` + Instructions())
}

// Instructions is the agent guidance, also printed by `gitident agent instructions`
// for AGENTS.md, CLAUDE.md or other agents' rule files.
func Instructions() string {
	return `# Git identity (gitident)

This machine manages git identities with gitident: every repository gets its
author name, email and signing key from a profile in
~/.config/gitident/profiles.yaml, chosen by directory, remote URL or an
explicit pin.

Before you commit, tag, merge, rebase, cherry-pick or pull, run:

    gitident preflight --json

- ` + "`\"ok\": true`" + `: go ahead.
- Otherwise every entry in ` + "`problems`" + ` has a ` + "`code`" + `, a ` + "`message`" + ` and a ` + "`fix`" + `.
  Exit status 1 means the identity is missing or wrong; 2 means only signing
  would fail.

Rules:

- Never set the identity yourself: no ` + "`git config user.name/user.email`" + `, no
  ` + "`git -c user.email=…`" + `, no GIT_AUTHOR_*/GIT_COMMITTER_* variables.
- Never turn signing off (` + "`--no-gpg-sign`" + `, ` + "`-c commit.gpgsign=false`" + `) unless
  the user says so.
- ` + "`no_identity`" + `, ` + "`unknown_email`" + `, ` + "`unmatched`" + `: ask the user which profile the
  repository belongs to, then run ` + "`gitident use <profile>`" + ` in it (add ` + "`--save`" + `
  to record it in profiles.yaml).
- ` + "`mismatch`" + `, ` + "`stale_copy`" + `: run ` + "`gitident sync`" + `, then preflight again.
- ` + "`signing_failed`" + `: the key needs a passphrase nobody can type here. Ask the
  user to unlock it (the fix says how), then retry.
- After cloning a repository, run ` + "`gitident preflight`" + ` in it before the first
  commit.

More: ` + "`gitident which --json`" + ` shows the effective identity and where it comes
from; ` + "`gitident check -q`" + ` lists repositories with identity problems.
`
}

// WriteSkill writes SKILL.md unless a different file not written by gitident
// is there. It returns whether the file changed.
func WriteSkill(path string, dryRun bool) (bool, error) {
	old, err := fsutil.ReadFileIfExists(path)
	if err != nil {
		return false, err
	}
	want := Skill()
	if string(old) == string(want) {
		return false, nil
	}
	if old != nil && !strings.Contains(string(old), skillMarker) {
		return false, fmt.Errorf("%s exists and was not written by gitident; not replacing it", paths.Contract(path))
	}
	if dryRun {
		return true, nil
	}
	return true, fsutil.WriteFileAtomic(path, want, 0o644)
}

// RemoveSkill deletes SKILL.md (and its directory) if gitident wrote it.
func RemoveSkill(path string, dryRun bool) (bool, error) {
	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !strings.Contains(string(data), skillMarker) {
		return false, nil
	}
	if dryRun {
		return true, nil
	}
	if err := os.Remove(path); err != nil {
		return false, err
	}
	_ = os.Remove(filepath.Dir(path))
	return true, nil
}
