package importer

import (
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/leoru/gitident-cli/internal/config"
	"github.com/leoru/gitident-cli/internal/paths"
)

// YAML renders the proposed profiles.yaml, with a "# source:" comment on every
// profile. Profiles appear in discovery order.
func (r *Result) YAML() ([]byte, error) {
	top := &yaml.Node{Kind: yaml.MappingNode}
	top.HeadComment = "generated by `" + paths.AppName + " import` — review, rename profiles, then run with --write\n" +
		"precedence: later rules win; a profile's repos beat all rules"
	addScalar(top, "version", fmt.Sprint(r.Config.Version), "!!int")
	if r.Config.StrictIdentity != nil {
		addScalar(top, "strict_identity", fmt.Sprint(*r.Config.StrictIdentity), "!!bool")
	}

	profiles := &yaml.Node{Kind: yaml.MappingNode}
	for _, name := range r.Order {
		var v yaml.Node
		if err := v.Encode(r.Config.Profiles[name]); err != nil {
			return nil, err
		}
		k := &yaml.Node{Kind: yaml.ScalarNode, Value: name, HeadComment: sourceComment(r.Sources[name])}
		profiles.Content = append(profiles.Content, k, &v)
	}
	top.Content = append(top.Content, &yaml.Node{Kind: yaml.ScalarNode, Value: "profiles"}, profiles)

	if len(r.Config.Rules) > 0 {
		var rules yaml.Node
		if err := rules.Encode(r.Config.Rules); err != nil {
			return nil, err
		}
		top.Content = append(top.Content, &yaml.Node{Kind: yaml.ScalarNode, Value: "rules"}, &rules)
	}
	return config.Marshal(&yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{top}})
}

func addScalar(m *yaml.Node, key, value, tag string) {
	m.Content = append(m.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value, Tag: tag})
}

func sourceComment(sources []string) string {
	lines := make([]string, len(sources))
	for i, s := range sources {
		lines[i] = "source: " + s
	}
	return strings.Join(lines, "\n")
}

// sameIdentity reports whether two profiles describe the same identity.
func sameIdentity(a, b *config.Profile) bool {
	boolStr := func(p *bool) string {
		if p == nil {
			return ""
		}
		return fmt.Sprint(*p)
	}
	return a.Name == b.Name && strings.EqualFold(a.Email, b.Email) && a.SigningKey == b.SigningKey &&
		a.GPGFormat == b.GPGFormat && boolStr(a.GPGSign) == boolStr(b.GPGSign) && a.SSHKey == b.SSHKey
}

// Merge adds the result's new profiles, repos and rules to an existing
// profiles.yaml, preserving its comments. Profiles whose identity already exists
// are mapped onto the existing profile; only repos not listed anywhere yet are
// added; missing extra keys are copied onto matched profiles; rules for newly
// created profiles are inserted at the start of `rules` (lowest precedence), so
// they never override the user's existing rules. It returns the new file
// content and a human-readable list of changes.
func Merge(existing []byte, r *Result) ([]byte, []string, error) {
	cur, err := config.Parse(existing)
	if err != nil {
		return nil, nil, err
	}
	doc, err := config.ParseDocument(existing)
	if err != nil {
		return nil, nil, err
	}
	owned := map[string]bool{}
	for _, p := range cur.Profiles {
		for _, repo := range p.Repos {
			owned[config.RepoKey(repo)] = true
		}
	}
	taken := map[string]bool{}
	for n := range cur.Profiles {
		taken[n] = true
	}

	var changes []string
	mapped := map[string]string{} // imported name → name in the merged file
	created := map[string]bool{}
	for _, name := range r.Order {
		p := r.Config.Profiles[name]
		for _, existingName := range cur.ProfileNames() {
			if sameIdentity(cur.Profiles[existingName], p) {
				mapped[name] = existingName
				break
			}
		}
		if target, ok := mapped[name]; ok {
			have := cur.Profiles[target].Extra
			for _, k := range sortedKeys(p.Extra) {
				switch old, exists := have[k]; {
				case !exists:
					if err := doc.SetExtra(target, k, p.Extra[k]); err != nil {
						return nil, nil, err
					}
					changes = append(changes, fmt.Sprintf("added extra %s = %s to profile %q", k, p.Extra[k], target))
				case old != p.Extra[k]:
					changes = append(changes, fmt.Sprintf("kept extra %s = %s in profile %q (import found %s)", k, old, target, p.Extra[k]))
				}
			}
			continue
		}
		newName := unique(name, taken)
		taken[newName] = true
		mapped[name], created[newName] = newName, true
		np := *p
		np.Repos = nil
		if err := doc.AddProfile(newName, &np, sourceComment(r.Sources[name])); err != nil {
			return nil, nil, err
		}
		changes = append(changes, fmt.Sprintf("added profile %q (%s <%s>)", newName, p.Name, p.Email))
	}
	for _, name := range r.Order {
		for _, repo := range r.Config.Profiles[name].Repos {
			key := config.RepoKey(repo)
			if owned[key] {
				continue
			}
			owned[key] = true
			if _, err := doc.AddRepo(mapped[name], repo); err != nil {
				return nil, nil, err
			}
			changes = append(changes, fmt.Sprintf("added repo %s to profile %q", repo, mapped[name]))
		}
	}
	var newRules []config.Rule
	for _, rule := range r.Config.Rules {
		target := mapped[rule.Profile]
		if !created[target] {
			continue
		}
		rule.Profile = target
		newRules = append(newRules, rule)
		changes = append(changes, fmt.Sprintf("added rule for profile %q (first in `rules`, so your existing rules still win)", target))
	}
	if len(newRules) > 0 {
		if err := doc.PrependRules(newRules); err != nil {
			return nil, nil, err
		}
	}
	out, err := doc.Bytes()
	if err != nil {
		return nil, nil, err
	}
	merged, err := config.Parse(out)
	if err != nil {
		return nil, nil, err
	}
	if rep := merged.Validate(); !rep.OK() {
		return nil, nil, fmt.Errorf("merged config is invalid: %s", strings.Join(rep.Errors, "; "))
	}
	return out, changes, nil
}
