package render

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/leoru/gitident-cli/internal/config"
	"github.com/leoru/gitident-cli/internal/match"
	"github.com/leoru/gitident-cli/internal/paths"
)

// Managed block markers in the global gitconfig.
const (
	BeginMarker = "# >>> " + paths.AppName + " managed block — edit " + paths.ConfigFileName + " and run `" + paths.AppName + " sync` >>>"
	EndMarker   = "# <<< " + paths.AppName + " managed block <<<"

	// Prefixes used to recognise the markers even if their wording changes later.
	beginPrefix = "# >>> " + paths.AppName + " managed block"
	endPrefix   = "# <<< " + paths.AppName + " managed block"
)

// Setting is one git config key and value that a profile sets.
type Setting struct{ Key, Value string }

// Settings returns every key a profile sets, in fragment order: user.*,
// commit.gpgsign, gpg.format, core.sshCommand, then extra keys sorted.
func Settings(p *config.Profile) []Setting {
	out := []Setting{{"user.name", p.Name}, {"user.email", p.Email}}
	if p.SigningKey != "" {
		out = append(out, Setting{"user.signingkey", signingKey(p)})
	}
	if p.GPGSign != nil {
		out = append(out, Setting{"commit.gpgsign", strconv.FormatBool(*p.GPGSign)})
	}
	if p.GPGFormat != "" {
		out = append(out, Setting{"gpg.format", p.GPGFormat})
	}
	if p.SSHKey != "" {
		out = append(out, Setting{"core.sshCommand", SSHCommand(p.SSHKey)})
	}
	return append(out, extraSettings(p.Extra)...)
}

// Fragment renders the gitconfig fragment for one profile.
func Fragment(name string, p *config.Profile) []byte {
	var ss sectionSet
	for _, s := range Settings(p) {
		sec, sub, key := SplitKey(s.Key)
		ss.get(sec, sub).add(key, s.Value)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by %s from profile %q — do not edit\n", paths.AppName, name)
	writeSections(&b, ss.list)
	return []byte(b.String())
}

// signingKey returns the user.signingkey value. SSH key paths are written expanded
// because not every git version expands "~" in user.signingkey.
func signingKey(p *config.Profile) string {
	if p.GPGFormat == "ssh" && config.IsSSHKeyPath(p.SigningKey) {
		return paths.Expand(p.SigningKey)
	}
	return p.SigningKey
}

// SSHCommand builds the core.sshCommand for a key. The command runs through a
// shell, so a plain "~/..." path is expanded there; paths needing quoting are
// expanded up front and single-quoted.
func SSHCommand(key string) string {
	const opts = " -o IdentitiesOnly=yes"
	if !strings.ContainsAny(key, " \t'\"\\$`;&|<>()*?[]#!{}") {
		return "ssh -i " + key + opts
	}
	k := paths.Expand(key)
	return "ssh -i '" + strings.ReplaceAll(k, "'", `'\''`) + "'" + opts
}

// SSHKeyFromCommand extracts the key path from a command produced by SSHCommand
// (or any "ssh -i <key> ..." command). It reports false for other shapes.
func SSHKeyFromCommand(cmd string) (string, bool) {
	fields := strings.Fields(cmd)
	if len(fields) < 3 || (fields[0] != "ssh" && !strings.HasSuffix(fields[0], "/ssh")) {
		return "", false
	}
	for i := 1; i+1 < len(fields); i++ {
		if fields[i] == "-i" {
			key := fields[i+1]
			if strings.HasPrefix(key, "'") || strings.HasPrefix(key, `"`) {
				return "", false // quoted paths with spaces: keep verbatim
			}
			for _, f := range fields[1:] {
				if f != "-i" && f != key && f != "-o" && !strings.HasPrefix(f, "IdentitiesOnly=") {
					return "", false // extra options we would lose
				}
			}
			return key, true
		}
	}
	return "", false
}

// StrictFragmentContent renders the fragment that turns on user.useConfigOnly.
// It lives in its own file, included from the block, so that the block contains
// no [user] section: `git config --global user.x ...` appends to the last
// [user] section in the file, and that must never be inside the block.
func StrictFragmentContent() []byte {
	return []byte("# generated by " + paths.AppName + " (strict_identity) — do not edit\n[user]\n\tuseConfigOnly = true\n")
}

// CloneFragmentContent renders the fragment that sets init.templateDir.
func CloneFragmentContent() []byte {
	return []byte("# generated by " + paths.AppName + " (clone_hook) — do not edit\n[init]\n\ttemplateDir = " + paths.TemplateDirTilde + "\n")
}

// HookScript is the post-checkout hook installed by clone_hook. After a clone
// or `git worktree add` (the previous HEAD is the null id) it runs
// `gitident __on-clone`, which reports the profile the repository gets and
// copies it into .git/config when materialize is on. It never fails the clone.
const HookScript = `#!/bin/sh
# generated by ` + paths.AppName + ` (clone_hook) — do not edit
# Runs after git clone / git worktree add: reports which gitident profile the
# new repository gets, and copies it into .git/config when materialize is on.
case "$1" in
  0000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000) ;;
  *) exit 0 ;;
esac
g=$(command -v gitident 2>/dev/null) || for p in /opt/homebrew/bin/gitident /usr/local/bin/gitident "$HOME/go/bin/gitident"; do
  [ -x "$p" ] && g=$p && break
done
[ -n "$g" ] || exit 0
"$g" __on-clone || true
exit 0
`

// Block renders the managed block, including markers, with LF line endings.
//
// Order inside the block is the precedence model (git applies later includes over
// earlier ones for single-valued keys):
//
//  1. user.useConfigOnly when strict_identity (via an included fragment)
//  2. rules in file order: dirs → includeIf gitdir:<dir>/, remotes → includeIf hasconfig:remote.*.url:<glob>
//  3. every profile's repos (profiles alphabetically): paths → gitdir:<path>/.git, URLs → hasconfig with and without .git
//
// Per-repo pins (`gitident use`) live in .git/config, which git reads after the
// global config, so they beat everything here.
//
// withClone adds the include of the clone_hook fragment (init.templateDir).
func Block(cfg *config.Config, withClone bool) []byte {
	var b strings.Builder
	b.WriteString(BeginMarker + "\n")
	b.WriteString("# Precedence: later entries win — rules (in file order), then per-profile repos.\n")
	b.WriteString("# Pins made with `" + paths.AppName + " use` live in .git/config and beat all of these.\n")

	var sections []*section
	if cfg.Strict() {
		s := &section{name: "include", comment: "# strict_identity: user.useConfigOnly = true"}
		s.add("path", paths.FragmentPathTilde(paths.StrictFragment))
		sections = append(sections, s)
	}
	if withClone {
		s := &section{name: "include", comment: "# clone_hook: init.templateDir with gitident's post-checkout hook"}
		s.add("path", paths.FragmentPathTilde(paths.CloneFragment))
		sections = append(sections, s)
	}
	for i, r := range cfg.Rules {
		comment := fmt.Sprintf("# rule %d → %s", i+1, r.Profile)
		for _, cond := range RuleConditions(r) {
			sections = append(sections, includeIf(cond, r.Profile, comment))
			comment = ""
		}
	}
	for _, name := range cfg.ProfileNames() {
		comment := fmt.Sprintf("# repos → %s", name)
		for _, repo := range cfg.Profiles[name].Repos {
			for _, cond := range RepoConditions(repo) {
				sections = append(sections, includeIf(cond, name, comment))
				comment = ""
			}
		}
	}
	writeSections(&b, sections)
	b.WriteString(EndMarker + "\n")
	return []byte(b.String())
}

func includeIf(cond, profile, comment string) *section {
	s := &section{name: "includeIf", sub: cond, comment: comment}
	s.add("path", paths.FragmentPathTilde(profile))
	return s
}

// RuleConditions returns the includeIf conditions for a rule, in order.
func RuleConditions(r config.Rule) []string {
	var conds []string
	for _, d := range r.Dirs {
		for _, p := range dirPatterns(d) {
			conds = append(conds, "gitdir:"+p+"/")
		}
	}
	for _, u := range r.Remotes {
		conds = append(conds, "hasconfig:remote.*.url:"+u)
	}
	return conds
}

// RepoConditions returns the includeIf conditions for one repos entry.
func RepoConditions(repo string) []string {
	if paths.IsURL(repo) {
		u := strings.TrimSuffix(strings.TrimRight(repo, "/"), ".git")
		return []string{"hasconfig:remote.*.url:" + u, "hasconfig:remote.*.url:" + u + ".git"}
	}
	var conds []string
	for _, p := range dirPatterns(repo) {
		conds = append(conds, "gitdir:"+p+"/.git")
	}
	return conds
}

// dirPatterns returns the gitdir pattern(s) for a directory, without a trailing
// slash: the path as written (~ form kept, git expands it), plus the
// symlink-resolved absolute path when that differs, since git only resolves
// symlinks on the repository side of the comparison.
func dirPatterns(dir string) []string {
	d := strings.TrimRight(dir, "/")
	out := []string{d}
	if match.HasGlob(d) {
		return out
	}
	abs := paths.Abs(d)
	if real := paths.Real(abs); real != abs {
		out = append(out, real)
	}
	return out
}
